name: Byg et Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker_image_pipeline:
    name: Build Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      IMAGE_NAME: auction-service
      IMAGE_VERSION: 0.2.0

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_VERSION} -f AuctionApi/Dockerfile ./AuctionApi

      - name: Push Docker image to Docker Hub
        run: docker push ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_VERSION}
